### ISSUE TITLE
Registry Object not present: biomemakeover:depth_curse

### ISSUE THREAD

**Issue by Sunconure11** [Lemonszz/Biome-Makeover#111]
https://bytebin.lucko.me/zuDYNfuAuP

**Comment by Lemonszz** [comment]
https://aofpaste.com/tafedufofo.yaml
Another crash, from the AoF team.

So far, I'm unable to recreate this on my end.

I have a feeling some other mod is breaking quite badly and BM is being blamed due to the frequency the crashing code is being called. 
In theory, if the crash is correct, the entirety of BM would be very broken, so I feel like some mod may be screwing with the registration process.

If anyone has any more information, please let me know!

**Comment by Sunconure11** [comment]
https://github.com/MoriyaShiine/enchancement

I’m wondering if this is involved, given how it changes enchantments

**Comment by Lemonszz** [comment]
Looks like it might be - I got the crash, though referencing a different enchantment. Good call.

https://gist.github.com/Lemonszz/bbbe44a6593c14ad894747e0d2025a2c

**Comment by Lemonszz** [comment]
Relevant Enhancement issue https://github.com/MoriyaShiine/enchancement/issues/6

**Comment by Lemonszz** [comment]
Fixed on enchancement's end.
