### ISSUE TITLE
Swamp like biomes from Biomes You'll Go seem te be overwritten by biome makeover

### ISSUE THREAD

**Issue by Jmulder08** [Lemonszz/Biome-Makeover#15]
When used in Combination with Biomes You'll Go, it seems Biome Makeover replaces the swampy biomes from BYG with it's own swamp biome (at least the vibrant and cold swampland biomes, cypress swamp did generate properly). Is this intended?

**Comment by Lemonszz** [comment]
It's supposed to generate it's features in any modded Biome marked as a "swamp".

It shouldn't replace any modded exclusive features, but it'll still replace vanilla-style swamp trees.

Feel free to post some screenshots if you think something is wrong, otherwise I'll check it out sometime in the future.

**Comment by Jmulder08** [comment]
Oh my bad, I thought it was weird that there were only biome makeover trees in the biomes, but the biomes I mentioned (vibrant swamplands and cold swamplands) normally only have vanilla-style trees, so it makes sense.
