### ISSUE TITLE
[1.20.1] Biome Makeover Crash

### ISSUE THREAD

**Issue by Peach774** [Lemonszz/Biome-Makeover#225]
Think this has to do with a change in forge in the newest recommended build.
https://hastebin.skyra.pw/rawaqemaqa.nestedtext

Disabling Biome Makeover fixes this issue, so if it isn't Forge, its some kind of conflict.

**Comment by Lemonszz** [comment]
Thanks - I'll look into this soon.

**Comment by wendall911** [comment]
I can get it to crash reliably with this: https://legacy.curseforge.com/minecraft/mc-mods/just-enough-resources-jer/files/4631691

I'm not sure what the issue is. It looks like a conflict with DefaultBiomesMixin_RemoveSwampTrees.java, causing the mixin to fail when calling: https://github.com/way2muchnoise/JustEnoughResources/blob/8cf16652efe0d038bbf312ecd1eef0d0c9921992/CommonApi/src/main/java/jeresources/api/util/BiomeHelper.java#L19

I spent a few minutes debugging this, but have no idea why it would fail to apply the mixin and crash when fetching a biome from the vanilla registry.

In this case it is a JER conflict, but doesn't look like a JER bug. I cant access the pastebin for this report to compare.

**Comment by Lemonszz** [comment]
Interesting - thanks for the information

**Comment by Lemonszz** [comment]
The version [here](https://modrinth.com/mod/biome-makeover/version/qr8qSbBf)  or [here ](https://legacy.curseforge.com/minecraft/mc-mods/biome-makeover-forge/files/4642570)(when approved) should fix it. 

Luckily the conflicting mixin was actually pointless and marked for removal lol

**Comment by wendall911** [comment]
Ok, yeah, that's much easier than debugging. I honestly have no clue why it crashed. 10.1.3 works perfectly! Thanks for the update, much appreciated.
