### ISSUE TITLE
Configuration Requests

### ISSUE THREAD

**Issue by Lemonszz** [Lemonszz/Biome-Makeover#65]
**We will not add configurations to turn off specific features of the mod.**  This is because pretty much everything links into other parts of the mod/vanilla. Turning off a feature will likely make other part of the mod inaccessible and I'd rather not support that.  

Ofc, you're welcome to configure the mod via other means (Crafttweaker, datapacks, resource packs etc).

But we're open to some config requests.  For example, a config to disable BM generation in specific biomes.  A use-case for this would be if another mod adds a "swamp-like" biome, but the BM generation and features don't really vibe aesthetically, you might want to turn them off.  This wouldn't break any progression (In most cases).

So if you're got any configuration requests, please leave them in this issue. No promises on adding any of them.

**Comment by legosteenjaap** [comment]
Ability to remove the extra biomemakeover tab and add the blocks to the normal vanilla tabs

**Comment by SplendidAlakey** [comment]
I'd love to have config options to configure spawn conditions for structures and geodes added by this mod. By default, I find them to be way too common, especially when used with other mods. Ideally, I'd like to see it implemented like in [Mo'Structures](https://www.curseforge.com/minecraft/mc-mods/mo-structures) or [Repurposed Structures](https://www.curseforge.com/minecraft/mc-mods/repurposed-structures-fabric), where you can specify a structure's spawn weight, min and max Y levels, amount of generation attempts per chunk, the amount of chunks required to be between the structures of the same type in order to attempt a spawn etc.

**Comment by Lemonszz** [comment]
That can all be done with datapacks, though I agree ideally it would be easier.

**Comment by Lemonszz** [comment]
Closed in favour for data pack configuration, see our discord "datapack-help" channel for more info. I'll hopefully get around to making a wiki soon.
